	Mk8_InlineController_CPU u0 (
		.altpll_sys_locked_conduit_export                 (<connected-to-altpll_sys_locked_conduit_export>),                 //               altpll_sys_locked_conduit.export
		.clk_clk                                          (<connected-to-clk_clk>),                                          //                                     clk.clk
		.clk_10m_clk                                      (<connected-to-clk_10m_clk>),                                      //                                 clk_10m.clk
		.clk_currctrl_fifo_clk                            (<connected-to-clk_currctrl_fifo_clk>),                            //                       clk_currctrl_fifo.clk
		.clk_currctrl_ram_clk                             (<connected-to-clk_currctrl_ram_clk>),                             //                        clk_currctrl_ram.clk
		.clk_parameter_ram_clk_clk                        (<connected-to-clk_parameter_ram_clk_clk>),                        //                   clk_parameter_ram_clk.clk
		.clk_usb_ext_clk_clk                              (<connected-to-clk_usb_ext_clk_clk>),                              //                         clk_usb_ext_clk.clk
		.cpu_clk_clk                                      (<connected-to-cpu_clk_clk>),                                      //                                 cpu_clk.clk
		.currctrl_sys_bridge_acknowledge                  (<connected-to-currctrl_sys_bridge_acknowledge>),                  //                     currctrl_sys_bridge.acknowledge
		.currctrl_sys_bridge_irq                          (<connected-to-currctrl_sys_bridge_irq>),                          //                                        .irq
		.currctrl_sys_bridge_address                      (<connected-to-currctrl_sys_bridge_address>),                      //                                        .address
		.currctrl_sys_bridge_bus_enable                   (<connected-to-currctrl_sys_bridge_bus_enable>),                   //                                        .bus_enable
		.currctrl_sys_bridge_byte_enable                  (<connected-to-currctrl_sys_bridge_byte_enable>),                  //                                        .byte_enable
		.currctrl_sys_bridge_rw                           (<connected-to-currctrl_sys_bridge_rw>),                           //                                        .rw
		.currctrl_sys_bridge_write_data                   (<connected-to-currctrl_sys_bridge_write_data>),                   //                                        .write_data
		.currctrl_sys_bridge_read_data                    (<connected-to-currctrl_sys_bridge_read_data>),                    //                                        .read_data
		.currctrl_sys_currctrl_gpio_ext_in_port           (<connected-to-currctrl_sys_currctrl_gpio_ext_in_port>),           //          currctrl_sys_currctrl_gpio_ext.in_port
		.currctrl_sys_currctrl_gpio_ext_out_port          (<connected-to-currctrl_sys_currctrl_gpio_ext_out_port>),          //                                        .out_port
		.currctrl_sys_register_ram_s2_address             (<connected-to-currctrl_sys_register_ram_s2_address>),             //            currctrl_sys_register_ram_s2.address
		.currctrl_sys_register_ram_s2_chipselect          (<connected-to-currctrl_sys_register_ram_s2_chipselect>),          //                                        .chipselect
		.currctrl_sys_register_ram_s2_clken               (<connected-to-currctrl_sys_register_ram_s2_clken>),               //                                        .clken
		.currctrl_sys_register_ram_s2_write               (<connected-to-currctrl_sys_register_ram_s2_write>),               //                                        .write
		.currctrl_sys_register_ram_s2_readdata            (<connected-to-currctrl_sys_register_ram_s2_readdata>),            //                                        .readdata
		.currctrl_sys_register_ram_s2_writedata           (<connected-to-currctrl_sys_register_ram_s2_writedata>),           //                                        .writedata
		.currctrl_sys_register_ram_s2_byteenable          (<connected-to-currctrl_sys_register_ram_s2_byteenable>),          //                                        .byteenable
		.parameter_sys_crc_init_bridge_acknowledge        (<connected-to-parameter_sys_crc_init_bridge_acknowledge>),        //           parameter_sys_crc_init_bridge.acknowledge
		.parameter_sys_crc_init_bridge_irq                (<connected-to-parameter_sys_crc_init_bridge_irq>),                //                                        .irq
		.parameter_sys_crc_init_bridge_address            (<connected-to-parameter_sys_crc_init_bridge_address>),            //                                        .address
		.parameter_sys_crc_init_bridge_bus_enable         (<connected-to-parameter_sys_crc_init_bridge_bus_enable>),         //                                        .bus_enable
		.parameter_sys_crc_init_bridge_byte_enable        (<connected-to-parameter_sys_crc_init_bridge_byte_enable>),        //                                        .byte_enable
		.parameter_sys_crc_init_bridge_rw                 (<connected-to-parameter_sys_crc_init_bridge_rw>),                 //                                        .rw
		.parameter_sys_crc_init_bridge_write_data         (<connected-to-parameter_sys_crc_init_bridge_write_data>),         //                                        .write_data
		.parameter_sys_crc_init_bridge_read_data          (<connected-to-parameter_sys_crc_init_bridge_read_data>),          //                                        .read_data
		.parameter_sys_parameter_gpio_in_port             (<connected-to-parameter_sys_parameter_gpio_in_port>),             //            parameter_sys_parameter_gpio.in_port
		.parameter_sys_parameter_gpio_out_port            (<connected-to-parameter_sys_parameter_gpio_out_port>),            //                                        .out_port
		.parameter_sys_parameter_rx_ram_s2_address        (<connected-to-parameter_sys_parameter_rx_ram_s2_address>),        //       parameter_sys_parameter_rx_ram_s2.address
		.parameter_sys_parameter_rx_ram_s2_chipselect     (<connected-to-parameter_sys_parameter_rx_ram_s2_chipselect>),     //                                        .chipselect
		.parameter_sys_parameter_rx_ram_s2_clken          (<connected-to-parameter_sys_parameter_rx_ram_s2_clken>),          //                                        .clken
		.parameter_sys_parameter_rx_ram_s2_write          (<connected-to-parameter_sys_parameter_rx_ram_s2_write>),          //                                        .write
		.parameter_sys_parameter_rx_ram_s2_readdata       (<connected-to-parameter_sys_parameter_rx_ram_s2_readdata>),       //                                        .readdata
		.parameter_sys_parameter_rx_ram_s2_writedata      (<connected-to-parameter_sys_parameter_rx_ram_s2_writedata>),      //                                        .writedata
		.parameter_sys_parameter_rx_ram_s2_byteenable     (<connected-to-parameter_sys_parameter_rx_ram_s2_byteenable>),     //                                        .byteenable
		.parameter_sys_parameter_tx_ram_s2_address        (<connected-to-parameter_sys_parameter_tx_ram_s2_address>),        //       parameter_sys_parameter_tx_ram_s2.address
		.parameter_sys_parameter_tx_ram_s2_chipselect     (<connected-to-parameter_sys_parameter_tx_ram_s2_chipselect>),     //                                        .chipselect
		.parameter_sys_parameter_tx_ram_s2_clken          (<connected-to-parameter_sys_parameter_tx_ram_s2_clken>),          //                                        .clken
		.parameter_sys_parameter_tx_ram_s2_write          (<connected-to-parameter_sys_parameter_tx_ram_s2_write>),          //                                        .write
		.parameter_sys_parameter_tx_ram_s2_readdata       (<connected-to-parameter_sys_parameter_tx_ram_s2_readdata>),       //                                        .readdata
		.parameter_sys_parameter_tx_ram_s2_writedata      (<connected-to-parameter_sys_parameter_tx_ram_s2_writedata>),      //                                        .writedata
		.parameter_sys_parameter_tx_ram_s2_byteenable     (<connected-to-parameter_sys_parameter_tx_ram_s2_byteenable>),     //                                        .byteenable
		.parameter_sys_parameterlengthpage_export         (<connected-to-parameter_sys_parameterlengthpage_export>),         //       parameter_sys_parameterlengthpage.export
		.pheriphals_led_gpio_external_connection_in_port  (<connected-to-pheriphals_led_gpio_external_connection_in_port>),  // pheriphals_led_gpio_external_connection.in_port
		.pheriphals_led_gpio_external_connection_out_port (<connected-to-pheriphals_led_gpio_external_connection_out_port>), //                                        .out_port
		.pheriphals_tp_gpio_external_connection_export    (<connected-to-pheriphals_tp_gpio_external_connection_export>),    //  pheriphals_tp_gpio_external_connection.export
		.reset_reset_n                                    (<connected-to-reset_reset_n>),                                    //                                   reset.reset_n
		.reset_currctrl_fifo_reset_n                      (<connected-to-reset_currctrl_fifo_reset_n>),                      //                     reset_currctrl_fifo.reset_n
		.reset_currctrl_ram_reset_n                       (<connected-to-reset_currctrl_ram_reset_n>),                       //                      reset_currctrl_ram.reset_n
		.reset_parameter_ram_clk_reset_n                  (<connected-to-reset_parameter_ram_clk_reset_n>),                  //                 reset_parameter_ram_clk.reset_n
		.reset_usb_ext_clk_reset_n                        (<connected-to-reset_usb_ext_clk_reset_n>),                        //                       reset_usb_ext_clk.reset_n
		.usb_data_sys_usb_data_gpio_in_port               (<connected-to-usb_data_sys_usb_data_gpio_in_port>),               //              usb_data_sys_usb_data_gpio.in_port
		.usb_data_sys_usb_data_gpio_out_port              (<connected-to-usb_data_sys_usb_data_gpio_out_port>),              //                                        .out_port
		.usb_data_sys_usb_data_ram_s2_address             (<connected-to-usb_data_sys_usb_data_ram_s2_address>),             //            usb_data_sys_usb_data_ram_s2.address
		.usb_data_sys_usb_data_ram_s2_chipselect          (<connected-to-usb_data_sys_usb_data_ram_s2_chipselect>),          //                                        .chipselect
		.usb_data_sys_usb_data_ram_s2_clken               (<connected-to-usb_data_sys_usb_data_ram_s2_clken>),               //                                        .clken
		.usb_data_sys_usb_data_ram_s2_write               (<connected-to-usb_data_sys_usb_data_ram_s2_write>),               //                                        .write
		.usb_data_sys_usb_data_ram_s2_readdata            (<connected-to-usb_data_sys_usb_data_ram_s2_readdata>),            //                                        .readdata
		.usb_data_sys_usb_data_ram_s2_writedata           (<connected-to-usb_data_sys_usb_data_ram_s2_writedata>),           //                                        .writedata
		.usb_data_sys_usb_data_ram_s2_byteenable          (<connected-to-usb_data_sys_usb_data_ram_s2_byteenable>)           //                                        .byteenable
	);

