/*
 * RegisterData_RX_Handler.h
 *
 *  Created on: 3 Jan 2021
 *      Author: Pete.Mayes
 */

#ifndef HANDLERS_USB_DATA_HANDLER_H_
#define HANDLERS_USB_DATA_HANDLER_H_

#define 	DATA_INTERFACE_RESET_STATE				0
#define		DATA_INTERFACE_IDLE_STATE				1
#define		DATA_INTERFACE_PATTERN_DATA_STATE		2
#define		DATA_INTERFACE_TABLE_UPDATE_STATE		3
#define		DATA_INTERFACE_FIRMWARE_UPDATE_STATE	4
#define		DATA_INTERFACE_NODE_COPY_MODE_STATE		5


#define 	PATTERN_DATA_RESET_STATE					0
#define		PATTERN_DATA_IDLE_STATE						1
#define		PATTERN_DATA_DOWNLOAD_DATA_STATE			2
#define		PATTERN_DATA_RUN_AND_BSD_IDLE_STATE			3
#define 	PATTERN_DATA_CRC_CHECK_STATE				4
#define  	PATTERN_DATA_CRC_WAIT_STATE					5
#define 	PATTERN_DATA_NORMAL_RUN_STATE				6
#define 	PATTERN_DATA_PRELOAD_STATE					7

#define		FT_600_ENTRY								0
//#define 	FT_RESET_STATE								1
#define 	FT_READY_TO_ACQUIRE_STATE					2
#define 	FT_ERASE_USB_USER_FLASH_STATE				3
#define 	FT_ERASE_FPGA_CONFIG_FLASH_STATE			8
#define 	FT_CRC_FPGA_CONFIG_DDR3_STATE				9
/*#define 	FT_ACQUIRE_STATE							3
#define		FT_600_SEND_INITIALISATION_DATA				4
#define		FT_DOWNLOAD_STATE							5
#define 	FT_DOWNLOAD_COMPLETE_STATE					6
#define 	FT_CRC_CALCULATION_STATE					7
#define 	FT_ERASE_USB_USER_FLASH_STATE				8
#define 	FT_PROGRAM_USB_USER_FLASH_STATE				9
#define 	FT_ERASE_USB_USER_FLASH_SUCCESS_STATE		10
#define 	FT_ERASE_USB_USER_FLASH_FAILED_STATE		11
#define 	FT_ERASE_SUPERVOSORY_USER_FLASH_STATE		12
#define 	FT_ERASE_FPGA_CONFIG_FLASH_STATE			13
#define 	FT_CRC_FPGA_CONFIG_DDR3_STATE				14
#define 	FT_CRC_USB_USER_DDR3_STATE					15
#define 	FT_CRC_SUPERVISORY_USER_DDR3_STATE			16*/

#define  	FT_CRC_OBSERVER_USER_FLASH_DDR3_STATE		22
#define 	FT_WAIT_FOR_REQUEST_FLAG_TO_BE_CLEARED		12
#define 	FT_ERASE_OBSERVER_USER_FLASH_STATE			4
#define 	FT_ERASE_USB_USER_FLASH_SUCCESS_STATE		5
#define 	FT_ERASE_USB_USER_FLASH_FAILED_STATE		6
#define 	FT_CRC_OBSERVER_CONFIG_FLASH_DDR3_STATE		7
//#define 	FT_ERASE_OBSERVER_CONFIG_FLASH_STATE		8
#define		FT_RESET_OBSERVER_CPLD_STATE				19


extern Uint32 Decode_USB_Text_String(void);
extern int32 USB_Data_CommsHandler(int16);
extern void DataInterfaceOperatingModeStatemachine(void);
extern Uint32 GetPatternDataOperatingState(void);

#endif /* HANDLERS_USB_DATA_HANDLER_H_ */
