/*
 * Types.h
 *
 *  Created on: 2 Sep 2014
 *      Author: prm
 */

#ifndef TYPES_H_
#define TYPES_H_

#define TRUE	0x55
#define FALSE	0

#define FORWARDS	0
#define BACKWARDS	1

#define STARBOARD_PITCH_CONTROLLER			1
#define PORT_PITCH_CONTROLLER				0


#define CONTROL_ARM_STARBOARD_UPPER_LIMIT		1155  // span is 1457 - midpoint is 730
#define CONTROL_ARM_STARBOARD_LOWER_LIMIT		2164
#define CONTROL_ARM_STARBOARD_MID_POINT			(CONTROL_ARM_STARBOARD_UPPER_LIMIT + CONTROL_ARM_STARBOARD_LOWER_LIMIT) / 2

#define CONTROL_ARM_PORT_UPPER_LIMIT			-825  // span is 1665 - mid point 832
#define CONTROL_ARM_PORT_LOWER_LIMIT			180
#define CONTROL_ARM_PORT_MID_POINT				(CONTROL_ARM_PORT_UPPER_LIMIT + CONTROL_ARM_PORT_LOWER_LIMIT) / 2


/*#define CONTROL_ARM_STARBOARD_UPPER_LIMIT		1155  // span is 1457 - midpoint is 730
#define CONTROL_ARM_STARBOARD_LOWER_LIMIT		2164
#define CONTROL_ARM_STARBOARD_MID_POINT			(CONTROL_ARM_STARBOARD_UPPER_LIMIT + CONTROL_ARM_STARBOARD_LOWER_LIMIT) / 2

#define CONTROL_ARM_PORT_UPPER_LIMIT			-825  // span is 1665 - mid point 832
#define CONTROL_ARM_PORT_LOWER_LIMIT			180
#define CONTROL_ARM_PORT_MID_POINT				(CONTROL_ARM_PORT_UPPER_LIMIT + CONTROL_ARM_PORT_LOWER_LIMIT) / 2*/


#define PITCH_STARBOARD_UPPER_LIMIT				1540  // span is 1969 - midpoint is 692
#define PITCH_STARBOARD_LOWER_LIMIT				-156
#define PITCH_STARBOARD_MID_POINT				(PITCH_STARBOARD_UPPER_LIMIT + PITCH_STARBOARD_LOWER_LIMIT) / 2
#define PITCH_STARBOARD_ENCODER_SPAN			699
#define PITCH_STARBOARD_ABSOLUTE_SPAN			(PITCH_STARBOARD_UPPER_LIMIT - PITCH_STARBOARD_LOWER_LIMIT)
#define PITCH_STARBOARD_SCALING_FACTOR			(PITCH_STARBOARD_ENCODER_SPAN * 4096UL) / PITCH_STARBOARD_ABSOLUTE_SPAN
#define PITCH_STARBOARD_INVERT_SCALE			-1

#define PITCH_PORT_UPPER_LIMIT					3034UL  // span is 1714 - mid point 2177; encoder span is 700, 8 revs of motor, 14 teeth gives 84 edges per rev
#define PITCH_PORT_LOWER_LIMIT					1320UL
#define PITCH_PORT_MID_POINT					(PITCH_PORT_UPPER_LIMIT + PITCH_PORT_LOWER_LIMIT) / 2
#define PITCH_PORT_ENCODER_SPAN					700
#define PITCH_PORT_ABSOLUTE_SPAN				(PITCH_PORT_UPPER_LIMIT - PITCH_PORT_LOWER_LIMIT)
#define PITCH_PORT_SCALING_FACTOR				((PITCH_PORT_ENCODER_SPAN * 4096UL) / PITCH_PORT_ABSOLUTE_SPAN)
#define PITCH_PORT_INVERT_SCALE					-1


/*
#define EXTERNAL_COUNT_SHARED_RAM_ADDR				SHARED_RAM_BASE
#define FAST_PARAMETER_TABLE_SHARED_RAM_ADDR		SHARED_RAM_BASE + 100
#define DRIVE_0_DEMAND_TABLE_SHARED_RAM_ADDR		SHARED_RAM_BASE + 200
#define DRIVE_1_DEMAND_TABLE_SHARED_RAM_ADDR		SHARED_RAM_BASE + 300
#define DEMAND_TABLE_INITIALISION_VALUES_ARRD		SHARED_RAM_BASE + 400
#define SLOW_PARAMETER_TABLE_SHARED_RAM_ADDR		SHARED_RAM_BASE + 500
#define SLOW_PARAMETER_0_TABLE_SHARED_RAM_ADDR		SLOW_PARAMETER_TABLE_SHARED_RAM_ADDR
#define SLOW_PARAMETER_1_TABLE_SHARED_RAM_ADDR		SLOW_PARAMETER_TABLE_SHARED_RAM_ADDR + 200

*/
typedef int bool;

	typedef signed short       int16;  // looks like a int is 64 bits;
	typedef signed long        int32;
	typedef long long          int64;
	typedef unsigned short     Uint16;
	typedef unsigned long      Uint32;
	typedef unsigned long long Uint64;
//	typedef float              float32;
//	typedef long double        float64;


#endif /* TYPES_H_ */
