/*
 * system.h - SOPC Builder system and BSP software package information
 *
 * Machine generated for CPU 'nios2_gen2' in SOPC Builder design 'Mk8_InlineController_CPU'
 * SOPC Builder design path: ../../Mk8_InlineController_CPU.sopcinfo
 *
 * Generated: Fri Feb 05 14:35:13 GMT 2021
 */

/*
 * DO NOT MODIFY THIS FILE
 *
 * Changing this file will have subtle consequences
 * which will almost certainly lead to a nonfunctioning
 * system. If you do modify this file, be aware that your
 * changes will be overwritten and lost when this file
 * is generated again.
 *
 * DO NOT MODIFY THIS FILE
 */

/*
 * License Agreement
 *
 * Copyright (c) 2008
 * Altera Corporation, San Jose, California, USA.
 * All rights reserved.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 * This agreement shall be governed in all respects by the laws of the State
 * of California and by the laws of the United States of America.
 */

#ifndef __SYSTEM_H_
#define __SYSTEM_H_

/* Include definitions from linker script generator */
#include "linker.h"


/*
 * CPU configuration
 *
 */

#define ALT_CPU_ARCHITECTURE "altera_nios2_gen2"
#define ALT_CPU_BIG_ENDIAN 0
#define ALT_CPU_BREAK_ADDR 0x00001820
#define ALT_CPU_CPU_ARCH_NIOS2_R1
#define ALT_CPU_CPU_FREQ 75000000u
#define ALT_CPU_CPU_ID_SIZE 1
#define ALT_CPU_CPU_ID_VALUE 0x00000000
#define ALT_CPU_CPU_IMPLEMENTATION "fast"
#define ALT_CPU_DATA_ADDR_WIDTH 0x1a
#define ALT_CPU_DCACHE_LINE_SIZE 0
#define ALT_CPU_DCACHE_LINE_SIZE_LOG2 0
#define ALT_CPU_DCACHE_SIZE 0
#define ALT_CPU_EIC_PRESENT
#define ALT_CPU_EXCEPTION_ADDR 0x00010020
#define ALT_CPU_FLASH_ACCELERATOR_LINES 0
#define ALT_CPU_FLASH_ACCELERATOR_LINE_SIZE 0
#define ALT_CPU_FLUSHDA_SUPPORTED
#define ALT_CPU_FREQ 75000000
#define ALT_CPU_HARDWARE_DIVIDE_PRESENT 0
#define ALT_CPU_HARDWARE_MULTIPLY_PRESENT 1
#define ALT_CPU_HARDWARE_MULX_PRESENT 1
#define ALT_CPU_HAS_DEBUG_CORE 1
#define ALT_CPU_HAS_DEBUG_STUB
#define ALT_CPU_HAS_EXTRA_EXCEPTION_INFO
#define ALT_CPU_HAS_ILLEGAL_INSTRUCTION_EXCEPTION
#define ALT_CPU_HAS_JMPI_INSTRUCTION
#define ALT_CPU_ICACHE_LINE_SIZE 32
#define ALT_CPU_ICACHE_LINE_SIZE_LOG2 5
#define ALT_CPU_ICACHE_SIZE 4096
#define ALT_CPU_INST_ADDR_WIDTH 0x11
#define ALT_CPU_NAME "nios2_gen2"
#define ALT_CPU_NUM_OF_SHADOW_REG_SETS 8
#define ALT_CPU_OCI_VERSION 1
#define ALT_CPU_RESET_ADDR 0x00010000


/*
 * CPU configuration (with legacy prefix - don't use these anymore)
 *
 */

#define NIOS2_BIG_ENDIAN 0
#define NIOS2_BREAK_ADDR 0x00001820
#define NIOS2_CPU_ARCH_NIOS2_R1
#define NIOS2_CPU_FREQ 75000000u
#define NIOS2_CPU_ID_SIZE 1
#define NIOS2_CPU_ID_VALUE 0x00000000
#define NIOS2_CPU_IMPLEMENTATION "fast"
#define NIOS2_DATA_ADDR_WIDTH 0x1a
#define NIOS2_DCACHE_LINE_SIZE 0
#define NIOS2_DCACHE_LINE_SIZE_LOG2 0
#define NIOS2_DCACHE_SIZE 0
#define NIOS2_EIC_PRESENT
#define NIOS2_EXCEPTION_ADDR 0x00010020
#define NIOS2_FLASH_ACCELERATOR_LINES 0
#define NIOS2_FLASH_ACCELERATOR_LINE_SIZE 0
#define NIOS2_FLUSHDA_SUPPORTED
#define NIOS2_HARDWARE_DIVIDE_PRESENT 0
#define NIOS2_HARDWARE_MULTIPLY_PRESENT 1
#define NIOS2_HARDWARE_MULX_PRESENT 1
#define NIOS2_HAS_DEBUG_CORE 1
#define NIOS2_HAS_DEBUG_STUB
#define NIOS2_HAS_EXTRA_EXCEPTION_INFO
#define NIOS2_HAS_ILLEGAL_INSTRUCTION_EXCEPTION
#define NIOS2_HAS_JMPI_INSTRUCTION
#define NIOS2_ICACHE_LINE_SIZE 32
#define NIOS2_ICACHE_LINE_SIZE_LOG2 5
#define NIOS2_ICACHE_SIZE 4096
#define NIOS2_INST_ADDR_WIDTH 0x11
#define NIOS2_NUM_OF_SHADOW_REG_SETS 8
#define NIOS2_OCI_VERSION 1
#define NIOS2_RESET_ADDR 0x00010000


/*
 * CurrCTRL_SYS_CurrCTRLSYS_Bridge configuration
 *
 */

#define ALT_MODULE_CLASS_CurrCTRL_SYS_CurrCTRLSYS_Bridge altera_up_avalon_to_external_bus_bridge
#define CURRCTRL_SYS_CURRCTRLSYS_BRIDGE_BASE 0x2000500
#define CURRCTRL_SYS_CURRCTRLSYS_BRIDGE_IRQ 9
#define CURRCTRL_SYS_CURRCTRLSYS_BRIDGE_IRQ_INTERRUPT_CONTROLLER_ID 0
#define CURRCTRL_SYS_CURRCTRLSYS_BRIDGE_NAME "/dev/CurrCTRL_SYS_CurrCTRLSYS_Bridge"
#define CURRCTRL_SYS_CURRCTRLSYS_BRIDGE_SPAN 128
#define CURRCTRL_SYS_CURRCTRLSYS_BRIDGE_TYPE "altera_up_avalon_to_external_bus_bridge"


/*
 * CurrCTRL_SYS_CurrCTRL_GPIO configuration
 *
 */

#define ALT_MODULE_CLASS_CurrCTRL_SYS_CurrCTRL_GPIO altera_avalon_pio
#define CURRCTRL_SYS_CURRCTRL_GPIO_BASE 0x2000660
#define CURRCTRL_SYS_CURRCTRL_GPIO_BIT_CLEARING_EDGE_REGISTER 0
#define CURRCTRL_SYS_CURRCTRL_GPIO_BIT_MODIFYING_OUTPUT_REGISTER 1
#define CURRCTRL_SYS_CURRCTRL_GPIO_CAPTURE 1
#define CURRCTRL_SYS_CURRCTRL_GPIO_DATA_WIDTH 32
#define CURRCTRL_SYS_CURRCTRL_GPIO_DO_TEST_BENCH_WIRING 1
#define CURRCTRL_SYS_CURRCTRL_GPIO_DRIVEN_SIM_VALUE 0
#define CURRCTRL_SYS_CURRCTRL_GPIO_EDGE_TYPE "FALLING"
#define CURRCTRL_SYS_CURRCTRL_GPIO_FREQ 50000000
#define CURRCTRL_SYS_CURRCTRL_GPIO_HAS_IN 1
#define CURRCTRL_SYS_CURRCTRL_GPIO_HAS_OUT 1
#define CURRCTRL_SYS_CURRCTRL_GPIO_HAS_TRI 0
#define CURRCTRL_SYS_CURRCTRL_GPIO_IRQ -1
#define CURRCTRL_SYS_CURRCTRL_GPIO_IRQ_INTERRUPT_CONTROLLER_ID -1
#define CURRCTRL_SYS_CURRCTRL_GPIO_IRQ_TYPE "NONE"
#define CURRCTRL_SYS_CURRCTRL_GPIO_NAME "/dev/CurrCTRL_SYS_CurrCTRL_GPIO"
#define CURRCTRL_SYS_CURRCTRL_GPIO_RESET_VALUE 0
#define CURRCTRL_SYS_CURRCTRL_GPIO_SPAN 32
#define CURRCTRL_SYS_CURRCTRL_GPIO_TYPE "altera_avalon_pio"


/*
 * CurrCTRL_SYS_CurrCTRL_Register_RAM configuration
 *
 */

#define ALT_MODULE_CLASS_CurrCTRL_SYS_CurrCTRL_Register_RAM altera_avalon_onchip_memory2
#define CURRCTRL_SYS_CURRCTRL_REGISTER_RAM_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define CURRCTRL_SYS_CURRCTRL_REGISTER_RAM_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define CURRCTRL_SYS_CURRCTRL_REGISTER_RAM_BASE 0x2000000
#define CURRCTRL_SYS_CURRCTRL_REGISTER_RAM_CONTENTS_INFO ""
#define CURRCTRL_SYS_CURRCTRL_REGISTER_RAM_DUAL_PORT 1
#define CURRCTRL_SYS_CURRCTRL_REGISTER_RAM_GUI_RAM_BLOCK_TYPE "AUTO"
#define CURRCTRL_SYS_CURRCTRL_REGISTER_RAM_INIT_CONTENTS_FILE "Mk8_InlineController_CPU_CurrCTRL_SYS_CurrCTRL_Register_RAM"
#define CURRCTRL_SYS_CURRCTRL_REGISTER_RAM_INIT_MEM_CONTENT 0
#define CURRCTRL_SYS_CURRCTRL_REGISTER_RAM_INSTANCE_ID "NONE"
#define CURRCTRL_SYS_CURRCTRL_REGISTER_RAM_IRQ -1
#define CURRCTRL_SYS_CURRCTRL_REGISTER_RAM_IRQ_INTERRUPT_CONTROLLER_ID -1
#define CURRCTRL_SYS_CURRCTRL_REGISTER_RAM_NAME "/dev/CurrCTRL_SYS_CurrCTRL_Register_RAM"
#define CURRCTRL_SYS_CURRCTRL_REGISTER_RAM_NON_DEFAULT_INIT_FILE_ENABLED 0
#define CURRCTRL_SYS_CURRCTRL_REGISTER_RAM_RAM_BLOCK_TYPE "AUTO"
#define CURRCTRL_SYS_CURRCTRL_REGISTER_RAM_READ_DURING_WRITE_MODE "DONT_CARE"
#define CURRCTRL_SYS_CURRCTRL_REGISTER_RAM_SINGLE_CLOCK_OP 0
#define CURRCTRL_SYS_CURRCTRL_REGISTER_RAM_SIZE_MULTIPLE 1
#define CURRCTRL_SYS_CURRCTRL_REGISTER_RAM_SIZE_VALUE 1024
#define CURRCTRL_SYS_CURRCTRL_REGISTER_RAM_SPAN 1024
#define CURRCTRL_SYS_CURRCTRL_REGISTER_RAM_TYPE "altera_avalon_onchip_memory2"
#define CURRCTRL_SYS_CURRCTRL_REGISTER_RAM_WRITABLE 1


/*
 * Custom instruction macros
 *
 */

#define ALT_CI_NIOS_CUSTOM_INSTR_FLOATING_POINT_2_0(n,A,B) __builtin_custom_inii(ALT_CI_NIOS_CUSTOM_INSTR_FLOATING_POINT_2_0_N+(n&ALT_CI_NIOS_CUSTOM_INSTR_FLOATING_POINT_2_0_N_MASK),(A),(B))
#define ALT_CI_NIOS_CUSTOM_INSTR_FLOATING_POINT_2_0_1(n,A,B) __builtin_custom_inii(ALT_CI_NIOS_CUSTOM_INSTR_FLOATING_POINT_2_0_1_N+(n&ALT_CI_NIOS_CUSTOM_INSTR_FLOATING_POINT_2_0_1_N_MASK),(A),(B))
#define ALT_CI_NIOS_CUSTOM_INSTR_FLOATING_POINT_2_0_1_FADDS_N ALT_CI_NIOS_CUSTOM_INSTR_FLOATING_POINT_2_0_1_N+5
#define ALT_CI_NIOS_CUSTOM_INSTR_FLOATING_POINT_2_0_1_FDIVS_N ALT_CI_NIOS_CUSTOM_INSTR_FLOATING_POINT_2_0_1_N+7
#define ALT_CI_NIOS_CUSTOM_INSTR_FLOATING_POINT_2_0_1_FIXSI_N ALT_CI_NIOS_CUSTOM_INSTR_FLOATING_POINT_2_0_1_N+1
#define ALT_CI_NIOS_CUSTOM_INSTR_FLOATING_POINT_2_0_1_FLOATIS_N ALT_CI_NIOS_CUSTOM_INSTR_FLOATING_POINT_2_0_1_N+2
#define ALT_CI_NIOS_CUSTOM_INSTR_FLOATING_POINT_2_0_1_FMULS_N ALT_CI_NIOS_CUSTOM_INSTR_FLOATING_POINT_2_0_1_N+4
#define ALT_CI_NIOS_CUSTOM_INSTR_FLOATING_POINT_2_0_1_FSUBS_N ALT_CI_NIOS_CUSTOM_INSTR_FLOATING_POINT_2_0_1_N+6
#define ALT_CI_NIOS_CUSTOM_INSTR_FLOATING_POINT_2_0_1_N 0xf8
#define ALT_CI_NIOS_CUSTOM_INSTR_FLOATING_POINT_2_0_1_N_MASK ((1<<3)-1)
#define ALT_CI_NIOS_CUSTOM_INSTR_FLOATING_POINT_2_0_1_ROUND_N ALT_CI_NIOS_CUSTOM_INSTR_FLOATING_POINT_2_0_1_N+0
#define ALT_CI_NIOS_CUSTOM_INSTR_FLOATING_POINT_2_0_FABSS_N ALT_CI_NIOS_CUSTOM_INSTR_FLOATING_POINT_2_0_N+0
#define ALT_CI_NIOS_CUSTOM_INSTR_FLOATING_POINT_2_0_FCMPEQS_N ALT_CI_NIOS_CUSTOM_INSTR_FLOATING_POINT_2_0_N+3
#define ALT_CI_NIOS_CUSTOM_INSTR_FLOATING_POINT_2_0_FCMPGES_N ALT_CI_NIOS_CUSTOM_INSTR_FLOATING_POINT_2_0_N+4
#define ALT_CI_NIOS_CUSTOM_INSTR_FLOATING_POINT_2_0_FCMPGTS_N ALT_CI_NIOS_CUSTOM_INSTR_FLOATING_POINT_2_0_N+5
#define ALT_CI_NIOS_CUSTOM_INSTR_FLOATING_POINT_2_0_FCMPLES_N ALT_CI_NIOS_CUSTOM_INSTR_FLOATING_POINT_2_0_N+6
#define ALT_CI_NIOS_CUSTOM_INSTR_FLOATING_POINT_2_0_FCMPLTS_N ALT_CI_NIOS_CUSTOM_INSTR_FLOATING_POINT_2_0_N+7
#define ALT_CI_NIOS_CUSTOM_INSTR_FLOATING_POINT_2_0_FCMPNES_N ALT_CI_NIOS_CUSTOM_INSTR_FLOATING_POINT_2_0_N+2
#define ALT_CI_NIOS_CUSTOM_INSTR_FLOATING_POINT_2_0_FMAXS_N ALT_CI_NIOS_CUSTOM_INSTR_FLOATING_POINT_2_0_N+8
#define ALT_CI_NIOS_CUSTOM_INSTR_FLOATING_POINT_2_0_FMINS_N ALT_CI_NIOS_CUSTOM_INSTR_FLOATING_POINT_2_0_N+9
#define ALT_CI_NIOS_CUSTOM_INSTR_FLOATING_POINT_2_0_FNEGS_N ALT_CI_NIOS_CUSTOM_INSTR_FLOATING_POINT_2_0_N+1
#define ALT_CI_NIOS_CUSTOM_INSTR_FLOATING_POINT_2_0_N 0xe0
#define ALT_CI_NIOS_CUSTOM_INSTR_FLOATING_POINT_2_0_N_MASK ((1<<4)-1)
#define fmaxf(A,B) __builtin_custom_fnff(ALT_CI_NIOS_CUSTOM_INSTR_FLOATING_POINT_2_0_FMAXS_N,(A),(B))
#define fminf(A,B) __builtin_custom_fnff(ALT_CI_NIOS_CUSTOM_INSTR_FLOATING_POINT_2_0_FMINS_N,(A),(B))
#define lroundf(A) __builtin_custom_inf(ALT_CI_NIOS_CUSTOM_INSTR_FLOATING_POINT_2_0_1_ROUND_N,(A))


/*
 * Data_Memory configuration
 *
 */

#define ALT_MODULE_CLASS_Data_Memory altera_avalon_onchip_memory2
#define DATA_MEMORY_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define DATA_MEMORY_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define DATA_MEMORY_BASE 0x18000
#define DATA_MEMORY_CONTENTS_INFO ""
#define DATA_MEMORY_DUAL_PORT 0
#define DATA_MEMORY_GUI_RAM_BLOCK_TYPE "AUTO"
#define DATA_MEMORY_INIT_CONTENTS_FILE "Mk8_InlineController_CPU_Data_Memory"
#define DATA_MEMORY_INIT_MEM_CONTENT 1
#define DATA_MEMORY_INSTANCE_ID "NONE"
#define DATA_MEMORY_IRQ -1
#define DATA_MEMORY_IRQ_INTERRUPT_CONTROLLER_ID -1
#define DATA_MEMORY_NAME "/dev/Data_Memory"
#define DATA_MEMORY_NON_DEFAULT_INIT_FILE_ENABLED 0
#define DATA_MEMORY_RAM_BLOCK_TYPE "AUTO"
#define DATA_MEMORY_READ_DURING_WRITE_MODE "DONT_CARE"
#define DATA_MEMORY_SINGLE_CLOCK_OP 0
#define DATA_MEMORY_SIZE_MULTIPLE 1
#define DATA_MEMORY_SIZE_VALUE 9216
#define DATA_MEMORY_SPAN 9216
#define DATA_MEMORY_TYPE "altera_avalon_onchip_memory2"
#define DATA_MEMORY_WRITABLE 1


/*
 * Define for each module class mastered by the CPU
 *
 */

#define __ALTERA_AVALON_ONCHIP_MEMORY2
#define __ALTERA_AVALON_PIO
#define __ALTERA_AVALON_TIMER
#define __ALTERA_MSGDMA
#define __ALTERA_NIOS2_GEN2
#define __ALTERA_NIOS_CUSTOM_INSTR_FLOATING_POINT_2
#define __ALTERA_UP_AVALON_TO_EXTERNAL_BUS_BRIDGE
#define __ALTERA_VIC
#define __ALTPLL


/*
 * Parameter_SYS_CRC_Init_Bridge configuration
 *
 */

#define ALT_MODULE_CLASS_Parameter_SYS_CRC_Init_Bridge altera_up_avalon_to_external_bus_bridge
#define PARAMETER_SYS_CRC_INIT_BRIDGE_BASE 0x2000400
#define PARAMETER_SYS_CRC_INIT_BRIDGE_IRQ 8
#define PARAMETER_SYS_CRC_INIT_BRIDGE_IRQ_INTERRUPT_CONTROLLER_ID 0
#define PARAMETER_SYS_CRC_INIT_BRIDGE_NAME "/dev/Parameter_SYS_CRC_Init_Bridge"
#define PARAMETER_SYS_CRC_INIT_BRIDGE_SPAN 256
#define PARAMETER_SYS_CRC_INIT_BRIDGE_TYPE "altera_up_avalon_to_external_bus_bridge"


/*
 * Parameter_SYS_ParameterLengthPage configuration
 *
 */

#define ALT_MODULE_CLASS_Parameter_SYS_ParameterLengthPage altera_avalon_pio
#define PARAMETER_SYS_PARAMETERLENGTHPAGE_BASE 0x2000680
#define PARAMETER_SYS_PARAMETERLENGTHPAGE_BIT_CLEARING_EDGE_REGISTER 0
#define PARAMETER_SYS_PARAMETERLENGTHPAGE_BIT_MODIFYING_OUTPUT_REGISTER 0
#define PARAMETER_SYS_PARAMETERLENGTHPAGE_CAPTURE 0
#define PARAMETER_SYS_PARAMETERLENGTHPAGE_DATA_WIDTH 16
#define PARAMETER_SYS_PARAMETERLENGTHPAGE_DO_TEST_BENCH_WIRING 0
#define PARAMETER_SYS_PARAMETERLENGTHPAGE_DRIVEN_SIM_VALUE 0
#define PARAMETER_SYS_PARAMETERLENGTHPAGE_EDGE_TYPE "NONE"
#define PARAMETER_SYS_PARAMETERLENGTHPAGE_FREQ 50000000
#define PARAMETER_SYS_PARAMETERLENGTHPAGE_HAS_IN 0
#define PARAMETER_SYS_PARAMETERLENGTHPAGE_HAS_OUT 1
#define PARAMETER_SYS_PARAMETERLENGTHPAGE_HAS_TRI 0
#define PARAMETER_SYS_PARAMETERLENGTHPAGE_IRQ -1
#define PARAMETER_SYS_PARAMETERLENGTHPAGE_IRQ_INTERRUPT_CONTROLLER_ID -1
#define PARAMETER_SYS_PARAMETERLENGTHPAGE_IRQ_TYPE "NONE"
#define PARAMETER_SYS_PARAMETERLENGTHPAGE_NAME "/dev/Parameter_SYS_ParameterLengthPage"
#define PARAMETER_SYS_PARAMETERLENGTHPAGE_RESET_VALUE 0
#define PARAMETER_SYS_PARAMETERLENGTHPAGE_SPAN 16
#define PARAMETER_SYS_PARAMETERLENGTHPAGE_TYPE "altera_avalon_pio"


/*
 * Parameter_SYS_Parameter_GPIO configuration
 *
 */

#define ALT_MODULE_CLASS_Parameter_SYS_Parameter_GPIO altera_avalon_pio
#define PARAMETER_SYS_PARAMETER_GPIO_BASE 0x2000620
#define PARAMETER_SYS_PARAMETER_GPIO_BIT_CLEARING_EDGE_REGISTER 0
#define PARAMETER_SYS_PARAMETER_GPIO_BIT_MODIFYING_OUTPUT_REGISTER 1
#define PARAMETER_SYS_PARAMETER_GPIO_CAPTURE 1
#define PARAMETER_SYS_PARAMETER_GPIO_DATA_WIDTH 1
#define PARAMETER_SYS_PARAMETER_GPIO_DO_TEST_BENCH_WIRING 1
#define PARAMETER_SYS_PARAMETER_GPIO_DRIVEN_SIM_VALUE 0
#define PARAMETER_SYS_PARAMETER_GPIO_EDGE_TYPE "FALLING"
#define PARAMETER_SYS_PARAMETER_GPIO_FREQ 50000000
#define PARAMETER_SYS_PARAMETER_GPIO_HAS_IN 1
#define PARAMETER_SYS_PARAMETER_GPIO_HAS_OUT 1
#define PARAMETER_SYS_PARAMETER_GPIO_HAS_TRI 0
#define PARAMETER_SYS_PARAMETER_GPIO_IRQ 3
#define PARAMETER_SYS_PARAMETER_GPIO_IRQ_INTERRUPT_CONTROLLER_ID 0
#define PARAMETER_SYS_PARAMETER_GPIO_IRQ_TYPE "EDGE"
#define PARAMETER_SYS_PARAMETER_GPIO_NAME "/dev/Parameter_SYS_Parameter_GPIO"
#define PARAMETER_SYS_PARAMETER_GPIO_RESET_VALUE 0
#define PARAMETER_SYS_PARAMETER_GPIO_SPAN 32
#define PARAMETER_SYS_PARAMETER_GPIO_TYPE "altera_avalon_pio"


/*
 * Parameter_SYS_Parameter_RX_RAM configuration
 *
 */

#define ALT_MODULE_CLASS_Parameter_SYS_Parameter_RX_RAM altera_avalon_onchip_memory2
#define PARAMETER_SYS_PARAMETER_RX_RAM_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define PARAMETER_SYS_PARAMETER_RX_RAM_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define PARAMETER_SYS_PARAMETER_RX_RAM_BASE 0x6000
#define PARAMETER_SYS_PARAMETER_RX_RAM_CONTENTS_INFO ""
#define PARAMETER_SYS_PARAMETER_RX_RAM_DUAL_PORT 1
#define PARAMETER_SYS_PARAMETER_RX_RAM_GUI_RAM_BLOCK_TYPE "AUTO"
#define PARAMETER_SYS_PARAMETER_RX_RAM_INIT_CONTENTS_FILE "Mk8_InlineController_CPU_Parameter_SYS_Parameter_RX_RAM"
#define PARAMETER_SYS_PARAMETER_RX_RAM_INIT_MEM_CONTENT 0
#define PARAMETER_SYS_PARAMETER_RX_RAM_INSTANCE_ID "NONE"
#define PARAMETER_SYS_PARAMETER_RX_RAM_IRQ -1
#define PARAMETER_SYS_PARAMETER_RX_RAM_IRQ_INTERRUPT_CONTROLLER_ID -1
#define PARAMETER_SYS_PARAMETER_RX_RAM_NAME "/dev/Parameter_SYS_Parameter_RX_RAM"
#define PARAMETER_SYS_PARAMETER_RX_RAM_NON_DEFAULT_INIT_FILE_ENABLED 0
#define PARAMETER_SYS_PARAMETER_RX_RAM_RAM_BLOCK_TYPE "AUTO"
#define PARAMETER_SYS_PARAMETER_RX_RAM_READ_DURING_WRITE_MODE "DONT_CARE"
#define PARAMETER_SYS_PARAMETER_RX_RAM_SINGLE_CLOCK_OP 0
#define PARAMETER_SYS_PARAMETER_RX_RAM_SIZE_MULTIPLE 1
#define PARAMETER_SYS_PARAMETER_RX_RAM_SIZE_VALUE 4100
#define PARAMETER_SYS_PARAMETER_RX_RAM_SPAN 4100
#define PARAMETER_SYS_PARAMETER_RX_RAM_TYPE "altera_avalon_onchip_memory2"
#define PARAMETER_SYS_PARAMETER_RX_RAM_WRITABLE 1


/*
 * Parameter_SYS_Parameter_TX_RAM configuration
 *
 */

#define ALT_MODULE_CLASS_Parameter_SYS_Parameter_TX_RAM altera_avalon_onchip_memory2
#define PARAMETER_SYS_PARAMETER_TX_RAM_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define PARAMETER_SYS_PARAMETER_TX_RAM_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define PARAMETER_SYS_PARAMETER_TX_RAM_BASE 0x101c000
#define PARAMETER_SYS_PARAMETER_TX_RAM_CONTENTS_INFO ""
#define PARAMETER_SYS_PARAMETER_TX_RAM_DUAL_PORT 1
#define PARAMETER_SYS_PARAMETER_TX_RAM_GUI_RAM_BLOCK_TYPE "AUTO"
#define PARAMETER_SYS_PARAMETER_TX_RAM_INIT_CONTENTS_FILE "Mk8_InlineController_CPU_Parameter_SYS_Parameter_TX_RAM"
#define PARAMETER_SYS_PARAMETER_TX_RAM_INIT_MEM_CONTENT 0
#define PARAMETER_SYS_PARAMETER_TX_RAM_INSTANCE_ID "NONE"
#define PARAMETER_SYS_PARAMETER_TX_RAM_IRQ -1
#define PARAMETER_SYS_PARAMETER_TX_RAM_IRQ_INTERRUPT_CONTROLLER_ID -1
#define PARAMETER_SYS_PARAMETER_TX_RAM_NAME "/dev/Parameter_SYS_Parameter_TX_RAM"
#define PARAMETER_SYS_PARAMETER_TX_RAM_NON_DEFAULT_INIT_FILE_ENABLED 0
#define PARAMETER_SYS_PARAMETER_TX_RAM_RAM_BLOCK_TYPE "AUTO"
#define PARAMETER_SYS_PARAMETER_TX_RAM_READ_DURING_WRITE_MODE "DONT_CARE"
#define PARAMETER_SYS_PARAMETER_TX_RAM_SINGLE_CLOCK_OP 0
#define PARAMETER_SYS_PARAMETER_TX_RAM_SIZE_MULTIPLE 1
#define PARAMETER_SYS_PARAMETER_TX_RAM_SIZE_VALUE 4100
#define PARAMETER_SYS_PARAMETER_TX_RAM_SPAN 4100
#define PARAMETER_SYS_PARAMETER_TX_RAM_TYPE "altera_avalon_onchip_memory2"
#define PARAMETER_SYS_PARAMETER_TX_RAM_WRITABLE 1


/*
 * Pheriphals_LED_GPIO configuration
 *
 */

#define ALT_MODULE_CLASS_Pheriphals_LED_GPIO altera_avalon_pio
#define PHERIPHALS_LED_GPIO_BASE 0x2000640
#define PHERIPHALS_LED_GPIO_BIT_CLEARING_EDGE_REGISTER 0
#define PHERIPHALS_LED_GPIO_BIT_MODIFYING_OUTPUT_REGISTER 1
#define PHERIPHALS_LED_GPIO_CAPTURE 0
#define PHERIPHALS_LED_GPIO_DATA_WIDTH 8
#define PHERIPHALS_LED_GPIO_DO_TEST_BENCH_WIRING 1
#define PHERIPHALS_LED_GPIO_DRIVEN_SIM_VALUE 0
#define PHERIPHALS_LED_GPIO_EDGE_TYPE "NONE"
#define PHERIPHALS_LED_GPIO_FREQ 50000000
#define PHERIPHALS_LED_GPIO_HAS_IN 1
#define PHERIPHALS_LED_GPIO_HAS_OUT 1
#define PHERIPHALS_LED_GPIO_HAS_TRI 0
#define PHERIPHALS_LED_GPIO_IRQ -1
#define PHERIPHALS_LED_GPIO_IRQ_INTERRUPT_CONTROLLER_ID -1
#define PHERIPHALS_LED_GPIO_IRQ_TYPE "NONE"
#define PHERIPHALS_LED_GPIO_NAME "/dev/Pheriphals_LED_GPIO"
#define PHERIPHALS_LED_GPIO_RESET_VALUE 0
#define PHERIPHALS_LED_GPIO_SPAN 32
#define PHERIPHALS_LED_GPIO_TYPE "altera_avalon_pio"


/*
 * Pheriphals_TP_GPIO configuration
 *
 */

#define ALT_MODULE_CLASS_Pheriphals_TP_GPIO altera_avalon_pio
#define PHERIPHALS_TP_GPIO_BASE 0x20005a0
#define PHERIPHALS_TP_GPIO_BIT_CLEARING_EDGE_REGISTER 0
#define PHERIPHALS_TP_GPIO_BIT_MODIFYING_OUTPUT_REGISTER 1
#define PHERIPHALS_TP_GPIO_CAPTURE 0
#define PHERIPHALS_TP_GPIO_DATA_WIDTH 8
#define PHERIPHALS_TP_GPIO_DO_TEST_BENCH_WIRING 0
#define PHERIPHALS_TP_GPIO_DRIVEN_SIM_VALUE 0
#define PHERIPHALS_TP_GPIO_EDGE_TYPE "NONE"
#define PHERIPHALS_TP_GPIO_FREQ 50000000
#define PHERIPHALS_TP_GPIO_HAS_IN 0
#define PHERIPHALS_TP_GPIO_HAS_OUT 1
#define PHERIPHALS_TP_GPIO_HAS_TRI 0
#define PHERIPHALS_TP_GPIO_IRQ -1
#define PHERIPHALS_TP_GPIO_IRQ_INTERRUPT_CONTROLLER_ID -1
#define PHERIPHALS_TP_GPIO_IRQ_TYPE "NONE"
#define PHERIPHALS_TP_GPIO_NAME "/dev/Pheriphals_TP_GPIO"
#define PHERIPHALS_TP_GPIO_RESET_VALUE 0
#define PHERIPHALS_TP_GPIO_SPAN 32
#define PHERIPHALS_TP_GPIO_TYPE "altera_avalon_pio"


/*
 * Program_Memory configuration
 *
 */

#define ALT_MODULE_CLASS_Program_Memory altera_avalon_onchip_memory2
#define PROGRAM_MEMORY_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define PROGRAM_MEMORY_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define PROGRAM_MEMORY_BASE 0x10000
#define PROGRAM_MEMORY_CONTENTS_INFO ""
#define PROGRAM_MEMORY_DUAL_PORT 0
#define PROGRAM_MEMORY_GUI_RAM_BLOCK_TYPE "AUTO"
#define PROGRAM_MEMORY_INIT_CONTENTS_FILE "Mk8_InlineController_CPU_Program_Memory"
#define PROGRAM_MEMORY_INIT_MEM_CONTENT 1
#define PROGRAM_MEMORY_INSTANCE_ID "NONE"
#define PROGRAM_MEMORY_IRQ -1
#define PROGRAM_MEMORY_IRQ_INTERRUPT_CONTROLLER_ID -1
#define PROGRAM_MEMORY_NAME "/dev/Program_Memory"
#define PROGRAM_MEMORY_NON_DEFAULT_INIT_FILE_ENABLED 0
#define PROGRAM_MEMORY_RAM_BLOCK_TYPE "AUTO"
#define PROGRAM_MEMORY_READ_DURING_WRITE_MODE "DONT_CARE"
#define PROGRAM_MEMORY_SINGLE_CLOCK_OP 0
#define PROGRAM_MEMORY_SIZE_MULTIPLE 1
#define PROGRAM_MEMORY_SIZE_VALUE 32768
#define PROGRAM_MEMORY_SPAN 32768
#define PROGRAM_MEMORY_TYPE "altera_avalon_onchip_memory2"
#define PROGRAM_MEMORY_WRITABLE 1


/*
 * System configuration
 *
 */

#define ALT_DEVICE_FAMILY "MAX 10"
#define ALT_ENHANCED_INTERRUPT_API_PRESENT
#define ALT_IRQ_BASE NULL
#define ALT_LOG_PORT "/dev/null"
#define ALT_LOG_PORT_BASE 0x0
#define ALT_LOG_PORT_DEV null
#define ALT_LOG_PORT_TYPE ""
#define ALT_NUM_EXTERNAL_INTERRUPT_CONTROLLERS 1
#define ALT_NUM_INTERNAL_INTERRUPT_CONTROLLERS 0
#define ALT_NUM_INTERRUPT_CONTROLLERS 1
#define ALT_STDERR "/dev/null"
#define ALT_STDERR_BASE 0x0
#define ALT_STDERR_DEV null
#define ALT_STDERR_TYPE ""
#define ALT_STDIN "/dev/null"
#define ALT_STDIN_BASE 0x0
#define ALT_STDIN_DEV null
#define ALT_STDIN_TYPE ""
#define ALT_STDOUT "/dev/null"
#define ALT_STDOUT_BASE 0x0
#define ALT_STDOUT_DEV null
#define ALT_STDOUT_TYPE ""
#define ALT_SYSTEM_NAME "Mk8_InlineController_CPU"


/*
 * TimerSYS_timer_0 configuration
 *
 */

#define ALT_MODULE_CLASS_TimerSYS_timer_0 altera_avalon_timer
#define TIMERSYS_TIMER_0_ALWAYS_RUN 0
#define TIMERSYS_TIMER_0_BASE 0x2000600
#define TIMERSYS_TIMER_0_COUNTER_SIZE 32
#define TIMERSYS_TIMER_0_FIXED_PERIOD 0
#define TIMERSYS_TIMER_0_FREQ 50000000
#define TIMERSYS_TIMER_0_IRQ 7
#define TIMERSYS_TIMER_0_IRQ_INTERRUPT_CONTROLLER_ID 0
#define TIMERSYS_TIMER_0_LOAD_VALUE 49999
#define TIMERSYS_TIMER_0_MULT 0.001
#define TIMERSYS_TIMER_0_NAME "/dev/TimerSYS_timer_0"
#define TIMERSYS_TIMER_0_PERIOD 1
#define TIMERSYS_TIMER_0_PERIOD_UNITS "ms"
#define TIMERSYS_TIMER_0_RESET_OUTPUT 0
#define TIMERSYS_TIMER_0_SNAPSHOT 1
#define TIMERSYS_TIMER_0_SPAN 32
#define TIMERSYS_TIMER_0_TICKS_PER_SEC 1000
#define TIMERSYS_TIMER_0_TIMEOUT_PULSE_OUTPUT 0
#define TIMERSYS_TIMER_0_TYPE "altera_avalon_timer"


/*
 * TimerSYS_timer_1 configuration
 *
 */

#define ALT_MODULE_CLASS_TimerSYS_timer_1 altera_avalon_timer
#define TIMERSYS_TIMER_1_ALWAYS_RUN 0
#define TIMERSYS_TIMER_1_BASE 0x20005e0
#define TIMERSYS_TIMER_1_COUNTER_SIZE 32
#define TIMERSYS_TIMER_1_FIXED_PERIOD 0
#define TIMERSYS_TIMER_1_FREQ 50000000
#define TIMERSYS_TIMER_1_IRQ 6
#define TIMERSYS_TIMER_1_IRQ_INTERRUPT_CONTROLLER_ID 0
#define TIMERSYS_TIMER_1_LOAD_VALUE 49999
#define TIMERSYS_TIMER_1_MULT 0.001
#define TIMERSYS_TIMER_1_NAME "/dev/TimerSYS_timer_1"
#define TIMERSYS_TIMER_1_PERIOD 1
#define TIMERSYS_TIMER_1_PERIOD_UNITS "ms"
#define TIMERSYS_TIMER_1_RESET_OUTPUT 0
#define TIMERSYS_TIMER_1_SNAPSHOT 1
#define TIMERSYS_TIMER_1_SPAN 32
#define TIMERSYS_TIMER_1_TICKS_PER_SEC 1000
#define TIMERSYS_TIMER_1_TIMEOUT_PULSE_OUTPUT 0
#define TIMERSYS_TIMER_1_TYPE "altera_avalon_timer"


/*
 * TimerSYS_timer_2 configuration
 *
 */

#define ALT_MODULE_CLASS_TimerSYS_timer_2 altera_avalon_timer
#define TIMERSYS_TIMER_2_ALWAYS_RUN 0
#define TIMERSYS_TIMER_2_BASE 0x20005c0
#define TIMERSYS_TIMER_2_COUNTER_SIZE 32
#define TIMERSYS_TIMER_2_FIXED_PERIOD 0
#define TIMERSYS_TIMER_2_FREQ 50000000
#define TIMERSYS_TIMER_2_IRQ 2
#define TIMERSYS_TIMER_2_IRQ_INTERRUPT_CONTROLLER_ID 0
#define TIMERSYS_TIMER_2_LOAD_VALUE 49999
#define TIMERSYS_TIMER_2_MULT 0.001
#define TIMERSYS_TIMER_2_NAME "/dev/TimerSYS_timer_2"
#define TIMERSYS_TIMER_2_PERIOD 1
#define TIMERSYS_TIMER_2_PERIOD_UNITS "ms"
#define TIMERSYS_TIMER_2_RESET_OUTPUT 0
#define TIMERSYS_TIMER_2_SNAPSHOT 1
#define TIMERSYS_TIMER_2_SPAN 32
#define TIMERSYS_TIMER_2_TICKS_PER_SEC 1000
#define TIMERSYS_TIMER_2_TIMEOUT_PULSE_OUTPUT 0
#define TIMERSYS_TIMER_2_TYPE "altera_avalon_timer"


/*
 * USB_Data_SYS_USB_GPIO configuration
 *
 */

#define ALT_MODULE_CLASS_USB_Data_SYS_USB_GPIO altera_avalon_pio
#define USB_DATA_SYS_USB_GPIO_BASE 0x2000580
#define USB_DATA_SYS_USB_GPIO_BIT_CLEARING_EDGE_REGISTER 0
#define USB_DATA_SYS_USB_GPIO_BIT_MODIFYING_OUTPUT_REGISTER 1
#define USB_DATA_SYS_USB_GPIO_CAPTURE 1
#define USB_DATA_SYS_USB_GPIO_DATA_WIDTH 1
#define USB_DATA_SYS_USB_GPIO_DO_TEST_BENCH_WIRING 1
#define USB_DATA_SYS_USB_GPIO_DRIVEN_SIM_VALUE 0
#define USB_DATA_SYS_USB_GPIO_EDGE_TYPE "FALLING"
#define USB_DATA_SYS_USB_GPIO_FREQ 50000000
#define USB_DATA_SYS_USB_GPIO_HAS_IN 1
#define USB_DATA_SYS_USB_GPIO_HAS_OUT 1
#define USB_DATA_SYS_USB_GPIO_HAS_TRI 0
#define USB_DATA_SYS_USB_GPIO_IRQ 4
#define USB_DATA_SYS_USB_GPIO_IRQ_INTERRUPT_CONTROLLER_ID 0
#define USB_DATA_SYS_USB_GPIO_IRQ_TYPE "EDGE"
#define USB_DATA_SYS_USB_GPIO_NAME "/dev/USB_Data_SYS_USB_GPIO"
#define USB_DATA_SYS_USB_GPIO_RESET_VALUE 0
#define USB_DATA_SYS_USB_GPIO_SPAN 32
#define USB_DATA_SYS_USB_GPIO_TYPE "altera_avalon_pio"


/*
 * USB_Data_SYS_USB_RX_RAM configuration
 *
 */

#define ALT_MODULE_CLASS_USB_Data_SYS_USB_RX_RAM altera_avalon_onchip_memory2
#define USB_DATA_SYS_USB_RX_RAM_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define USB_DATA_SYS_USB_RX_RAM_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define USB_DATA_SYS_USB_RX_RAM_BASE 0x4000
#define USB_DATA_SYS_USB_RX_RAM_CONTENTS_INFO ""
#define USB_DATA_SYS_USB_RX_RAM_DUAL_PORT 1
#define USB_DATA_SYS_USB_RX_RAM_GUI_RAM_BLOCK_TYPE "AUTO"
#define USB_DATA_SYS_USB_RX_RAM_INIT_CONTENTS_FILE "Mk8_InlineController_CPU_USB_Data_SYS_USB_RX_RAM"
#define USB_DATA_SYS_USB_RX_RAM_INIT_MEM_CONTENT 0
#define USB_DATA_SYS_USB_RX_RAM_INSTANCE_ID "NONE"
#define USB_DATA_SYS_USB_RX_RAM_IRQ -1
#define USB_DATA_SYS_USB_RX_RAM_IRQ_INTERRUPT_CONTROLLER_ID -1
#define USB_DATA_SYS_USB_RX_RAM_NAME "/dev/USB_Data_SYS_USB_RX_RAM"
#define USB_DATA_SYS_USB_RX_RAM_NON_DEFAULT_INIT_FILE_ENABLED 0
#define USB_DATA_SYS_USB_RX_RAM_RAM_BLOCK_TYPE "AUTO"
#define USB_DATA_SYS_USB_RX_RAM_READ_DURING_WRITE_MODE "DONT_CARE"
#define USB_DATA_SYS_USB_RX_RAM_SINGLE_CLOCK_OP 0
#define USB_DATA_SYS_USB_RX_RAM_SIZE_MULTIPLE 1
#define USB_DATA_SYS_USB_RX_RAM_SIZE_VALUE 4100
#define USB_DATA_SYS_USB_RX_RAM_SPAN 4100
#define USB_DATA_SYS_USB_RX_RAM_TYPE "altera_avalon_onchip_memory2"
#define USB_DATA_SYS_USB_RX_RAM_WRITABLE 1


/*
 * altera_vic_driver configuration
 *
 */

#define ALTERA_VIC_DRIVER_ENABLE_PREEMPTION_RS_0 0
#define ALTERA_VIC_DRIVER_ENABLE_PREEMPTION_RS_1 0
#define ALTERA_VIC_DRIVER_ENABLE_PREEMPTION_RS_2 0
#define ALTERA_VIC_DRIVER_ENABLE_PREEMPTION_RS_3 0
#define ALTERA_VIC_DRIVER_ENABLE_PREEMPTION_RS_4 0
#define ALTERA_VIC_DRIVER_ENABLE_PREEMPTION_RS_5 0
#define ALTERA_VIC_DRIVER_ENABLE_PREEMPTION_RS_6 0
#define ALTERA_VIC_DRIVER_ENABLE_PREEMPTION_RS_7 0
#define ALTERA_VIC_DRIVER_ENABLE_PREEMPTION_RS_8 0
#define ALTERA_VIC_DRIVER_ISR_PREEMPTION_ENABLED
#define ALTERA_VIC_DRIVER_LINKER_SECTION .text
#define ALTERA_VIC_DRIVER_PREEMPTION_INTO_NEW_REGISTER_SET_ENABLED
#define ALTERA_VIC_DRIVER_VIC_0_IRQ0_RIL 15
#define ALTERA_VIC_DRIVER_VIC_0_IRQ0_RNMI 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ0_RRS 8
#define ALTERA_VIC_DRIVER_VIC_0_IRQ10_RIL 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ10_RNMI 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ10_RRS 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ11_RIL 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ11_RNMI 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ11_RRS 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ12_RIL 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ12_RNMI 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ12_RRS 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ13_RIL 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ13_RNMI 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ13_RRS 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ14_RIL 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ14_RNMI 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ14_RRS 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ15_RIL 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ15_RNMI 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ15_RRS 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ16_RIL 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ16_RNMI 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ16_RRS 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ17_RIL 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ17_RNMI 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ17_RRS 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ18_RIL 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ18_RNMI 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ18_RRS 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ19_RIL 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ19_RNMI 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ19_RRS 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ1_RIL 14
#define ALTERA_VIC_DRIVER_VIC_0_IRQ1_RNMI 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ1_RRS 7
#define ALTERA_VIC_DRIVER_VIC_0_IRQ20_RIL 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ20_RNMI 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ20_RRS 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ21_RIL 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ21_RNMI 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ21_RRS 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ22_RIL 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ22_RNMI 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ22_RRS 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ23_RIL 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ23_RNMI 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ23_RRS 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ24_RIL 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ24_RNMI 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ24_RRS 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ25_RIL 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ25_RNMI 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ25_RRS 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ26_RIL 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ26_RNMI 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ26_RRS 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ27_RIL 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ27_RNMI 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ27_RRS 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ28_RIL 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ28_RNMI 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ28_RRS 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ29_RIL 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ29_RNMI 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ29_RRS 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ2_RIL 13
#define ALTERA_VIC_DRIVER_VIC_0_IRQ2_RNMI 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ2_RRS 6
#define ALTERA_VIC_DRIVER_VIC_0_IRQ30_RIL 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ30_RNMI 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ30_RRS 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ31_RIL 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ31_RNMI 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ31_RRS 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ3_RIL 12
#define ALTERA_VIC_DRIVER_VIC_0_IRQ3_RNMI 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ3_RRS 5
#define ALTERA_VIC_DRIVER_VIC_0_IRQ4_RIL 11
#define ALTERA_VIC_DRIVER_VIC_0_IRQ4_RNMI 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ4_RRS 4
#define ALTERA_VIC_DRIVER_VIC_0_IRQ5_RIL 10
#define ALTERA_VIC_DRIVER_VIC_0_IRQ5_RNMI 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ5_RRS 3
#define ALTERA_VIC_DRIVER_VIC_0_IRQ6_RIL 9
#define ALTERA_VIC_DRIVER_VIC_0_IRQ6_RNMI 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ6_RRS 2
#define ALTERA_VIC_DRIVER_VIC_0_IRQ7_RIL 8
#define ALTERA_VIC_DRIVER_VIC_0_IRQ7_RNMI 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ7_RRS 1
#define ALTERA_VIC_DRIVER_VIC_0_IRQ8_RIL 7
#define ALTERA_VIC_DRIVER_VIC_0_IRQ8_RNMI 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ8_RRS 1
#define ALTERA_VIC_DRIVER_VIC_0_IRQ9_RIL 6
#define ALTERA_VIC_DRIVER_VIC_0_IRQ9_RNMI 0
#define ALTERA_VIC_DRIVER_VIC_0_IRQ9_RRS 1
#define VIC_0_VEC_SIZE 16
#define VIC_0_VEC_TBL_BASE VIC_0_VECTOR_TABLE


/*
 * altpll_sys configuration
 *
 */

#define ALTPLL_SYS_BASE 0x2c40
#define ALTPLL_SYS_IRQ -1
#define ALTPLL_SYS_IRQ_INTERRUPT_CONTROLLER_ID -1
#define ALTPLL_SYS_NAME "/dev/altpll_sys"
#define ALTPLL_SYS_SPAN 16
#define ALTPLL_SYS_TYPE "altpll"
#define ALT_MODULE_CLASS_altpll_sys altpll


/*
 * hal configuration
 *
 */

#define ALT_INCLUDE_INSTRUCTION_RELATED_EXCEPTION_API
#define ALT_MAX_FD 32
#define ALT_SYS_CLK none
#define ALT_TIMESTAMP_CLK none


/*
 * msgdma_0_csr configuration
 *
 */

#define ALT_MODULE_CLASS_msgdma_0_csr altera_msgdma
#define MSGDMA_0_CSR_BASE 0x1020000
#define MSGDMA_0_CSR_BURST_ENABLE 0
#define MSGDMA_0_CSR_BURST_WRAPPING_SUPPORT 0
#define MSGDMA_0_CSR_CHANNEL_ENABLE 0
#define MSGDMA_0_CSR_CHANNEL_ENABLE_DERIVED 0
#define MSGDMA_0_CSR_CHANNEL_WIDTH 8
#define MSGDMA_0_CSR_DATA_FIFO_DEPTH 32
#define MSGDMA_0_CSR_DATA_WIDTH 32
#define MSGDMA_0_CSR_DESCRIPTOR_FIFO_DEPTH 128
#define MSGDMA_0_CSR_DMA_MODE 0
#define MSGDMA_0_CSR_ENHANCED_FEATURES 1
#define MSGDMA_0_CSR_ERROR_ENABLE 0
#define MSGDMA_0_CSR_ERROR_ENABLE_DERIVED 0
#define MSGDMA_0_CSR_ERROR_WIDTH 8
#define MSGDMA_0_CSR_IRQ 1
#define MSGDMA_0_CSR_IRQ_INTERRUPT_CONTROLLER_ID 0
#define MSGDMA_0_CSR_MAX_BURST_COUNT 2
#define MSGDMA_0_CSR_MAX_BYTE 8192
#define MSGDMA_0_CSR_MAX_STRIDE 1
#define MSGDMA_0_CSR_NAME "/dev/msgdma_0_csr"
#define MSGDMA_0_CSR_PACKET_ENABLE 0
#define MSGDMA_0_CSR_PACKET_ENABLE_DERIVED 0
#define MSGDMA_0_CSR_PREFETCHER_ENABLE 0
#define MSGDMA_0_CSR_PROGRAMMABLE_BURST_ENABLE 0
#define MSGDMA_0_CSR_RESPONSE_PORT 2
#define MSGDMA_0_CSR_SPAN 32
#define MSGDMA_0_CSR_STRIDE_ENABLE 1
#define MSGDMA_0_CSR_STRIDE_ENABLE_DERIVED 1
#define MSGDMA_0_CSR_TRANSFER_TYPE "Full Word Accesses Only"
#define MSGDMA_0_CSR_TYPE "altera_msgdma"


/*
 * msgdma_0_descriptor_slave configuration
 *
 */

#define ALT_MODULE_CLASS_msgdma_0_descriptor_slave altera_msgdma
#define MSGDMA_0_DESCRIPTOR_SLAVE_BASE 0x1020020
#define MSGDMA_0_DESCRIPTOR_SLAVE_BURST_ENABLE 0
#define MSGDMA_0_DESCRIPTOR_SLAVE_BURST_WRAPPING_SUPPORT 0
#define MSGDMA_0_DESCRIPTOR_SLAVE_CHANNEL_ENABLE 0
#define MSGDMA_0_DESCRIPTOR_SLAVE_CHANNEL_ENABLE_DERIVED 0
#define MSGDMA_0_DESCRIPTOR_SLAVE_CHANNEL_WIDTH 8
#define MSGDMA_0_DESCRIPTOR_SLAVE_DATA_FIFO_DEPTH 32
#define MSGDMA_0_DESCRIPTOR_SLAVE_DATA_WIDTH 32
#define MSGDMA_0_DESCRIPTOR_SLAVE_DESCRIPTOR_FIFO_DEPTH 128
#define MSGDMA_0_DESCRIPTOR_SLAVE_DMA_MODE 0
#define MSGDMA_0_DESCRIPTOR_SLAVE_ENHANCED_FEATURES 1
#define MSGDMA_0_DESCRIPTOR_SLAVE_ERROR_ENABLE 0
#define MSGDMA_0_DESCRIPTOR_SLAVE_ERROR_ENABLE_DERIVED 0
#define MSGDMA_0_DESCRIPTOR_SLAVE_ERROR_WIDTH 8
#define MSGDMA_0_DESCRIPTOR_SLAVE_IRQ -1
#define MSGDMA_0_DESCRIPTOR_SLAVE_IRQ_INTERRUPT_CONTROLLER_ID -1
#define MSGDMA_0_DESCRIPTOR_SLAVE_MAX_BURST_COUNT 2
#define MSGDMA_0_DESCRIPTOR_SLAVE_MAX_BYTE 8192
#define MSGDMA_0_DESCRIPTOR_SLAVE_MAX_STRIDE 1
#define MSGDMA_0_DESCRIPTOR_SLAVE_NAME "/dev/msgdma_0_descriptor_slave"
#define MSGDMA_0_DESCRIPTOR_SLAVE_PACKET_ENABLE 0
#define MSGDMA_0_DESCRIPTOR_SLAVE_PACKET_ENABLE_DERIVED 0
#define MSGDMA_0_DESCRIPTOR_SLAVE_PREFETCHER_ENABLE 0
#define MSGDMA_0_DESCRIPTOR_SLAVE_PROGRAMMABLE_BURST_ENABLE 0
#define MSGDMA_0_DESCRIPTOR_SLAVE_RESPONSE_PORT 2
#define MSGDMA_0_DESCRIPTOR_SLAVE_SPAN 32
#define MSGDMA_0_DESCRIPTOR_SLAVE_STRIDE_ENABLE 1
#define MSGDMA_0_DESCRIPTOR_SLAVE_STRIDE_ENABLE_DERIVED 1
#define MSGDMA_0_DESCRIPTOR_SLAVE_TRANSFER_TYPE "Full Word Accesses Only"
#define MSGDMA_0_DESCRIPTOR_SLAVE_TYPE "altera_msgdma"


/*
 * vic_0 configuration
 *
 */

#define ALT_MODULE_CLASS_vic_0 altera_vic
#define VIC_0_BASE 0x2800
#define VIC_0_DAISY_CHAIN_ENABLE 0
#define VIC_0_INTERRUPT_CONTROLLER_ID 0
#define VIC_0_IRQ -1
#define VIC_0_IRQ_INTERRUPT_CONTROLLER_ID -1
#define VIC_0_NAME "/dev/vic_0"
#define VIC_0_NUMBER_OF_INT_PORTS 10
#define VIC_0_RIL_WIDTH 4
#define VIC_0_SPAN 1024
#define VIC_0_TYPE "altera_vic"

#endif /* __SYSTEM_H_ */
