	Pararameter_Comms_SYS u0 (
		.clk_ext_ram_clk                                (<connected-to-clk_ext_ram_clk>),                                //                        clk_ext_ram.clk
		.parameter_gpio_s1_address                      (<connected-to-parameter_gpio_s1_address>),                      //                  parameter_gpio_s1.address
		.parameter_gpio_s1_write_n                      (<connected-to-parameter_gpio_s1_write_n>),                      //                                   .write_n
		.parameter_gpio_s1_writedata                    (<connected-to-parameter_gpio_s1_writedata>),                    //                                   .writedata
		.parameter_gpio_s1_chipselect                   (<connected-to-parameter_gpio_s1_chipselect>),                   //                                   .chipselect
		.parameter_gpio_s1_readdata                     (<connected-to-parameter_gpio_s1_readdata>),                     //                                   .readdata
		.parameter_loop_gpio_irq_irq                    (<connected-to-parameter_loop_gpio_irq_irq>),                    //            parameter_loop_gpio_irq.irq
		.reset_ext_ram_reset_n                          (<connected-to-reset_ext_ram_reset_n>),                          //                      reset_ext_ram.reset_n
		.parameter_rx_ram_s1_address                    (<connected-to-parameter_rx_ram_s1_address>),                    //                parameter_rx_ram_s1.address
		.parameter_rx_ram_s1_clken                      (<connected-to-parameter_rx_ram_s1_clken>),                      //                                   .clken
		.parameter_rx_ram_s1_chipselect                 (<connected-to-parameter_rx_ram_s1_chipselect>),                 //                                   .chipselect
		.parameter_rx_ram_s1_write                      (<connected-to-parameter_rx_ram_s1_write>),                      //                                   .write
		.parameter_rx_ram_s1_readdata                   (<connected-to-parameter_rx_ram_s1_readdata>),                   //                                   .readdata
		.parameter_rx_ram_s1_writedata                  (<connected-to-parameter_rx_ram_s1_writedata>),                  //                                   .writedata
		.parameter_rx_ram_s1_byteenable                 (<connected-to-parameter_rx_ram_s1_byteenable>),                 //                                   .byteenable
		.parameter_rx_ram_s2_address                    (<connected-to-parameter_rx_ram_s2_address>),                    //                parameter_rx_ram_s2.address
		.parameter_rx_ram_s2_chipselect                 (<connected-to-parameter_rx_ram_s2_chipselect>),                 //                                   .chipselect
		.parameter_rx_ram_s2_clken                      (<connected-to-parameter_rx_ram_s2_clken>),                      //                                   .clken
		.parameter_rx_ram_s2_write                      (<connected-to-parameter_rx_ram_s2_write>),                      //                                   .write
		.parameter_rx_ram_s2_readdata                   (<connected-to-parameter_rx_ram_s2_readdata>),                   //                                   .readdata
		.parameter_rx_ram_s2_writedata                  (<connected-to-parameter_rx_ram_s2_writedata>),                  //                                   .writedata
		.parameter_rx_ram_s2_byteenable                 (<connected-to-parameter_rx_ram_s2_byteenable>),                 //                                   .byteenable
		.parameter_tx_ram_s1_address                    (<connected-to-parameter_tx_ram_s1_address>),                    //                parameter_tx_ram_s1.address
		.parameter_tx_ram_s1_clken                      (<connected-to-parameter_tx_ram_s1_clken>),                      //                                   .clken
		.parameter_tx_ram_s1_chipselect                 (<connected-to-parameter_tx_ram_s1_chipselect>),                 //                                   .chipselect
		.parameter_tx_ram_s1_write                      (<connected-to-parameter_tx_ram_s1_write>),                      //                                   .write
		.parameter_tx_ram_s1_readdata                   (<connected-to-parameter_tx_ram_s1_readdata>),                   //                                   .readdata
		.parameter_tx_ram_s1_writedata                  (<connected-to-parameter_tx_ram_s1_writedata>),                  //                                   .writedata
		.parameter_tx_ram_s1_byteenable                 (<connected-to-parameter_tx_ram_s1_byteenable>),                 //                                   .byteenable
		.parameter_tx_ram_s2_address                    (<connected-to-parameter_tx_ram_s2_address>),                    //                parameter_tx_ram_s2.address
		.parameter_tx_ram_s2_chipselect                 (<connected-to-parameter_tx_ram_s2_chipselect>),                 //                                   .chipselect
		.parameter_tx_ram_s2_clken                      (<connected-to-parameter_tx_ram_s2_clken>),                      //                                   .clken
		.parameter_tx_ram_s2_write                      (<connected-to-parameter_tx_ram_s2_write>),                      //                                   .write
		.parameter_tx_ram_s2_readdata                   (<connected-to-parameter_tx_ram_s2_readdata>),                   //                                   .readdata
		.parameter_tx_ram_s2_writedata                  (<connected-to-parameter_tx_ram_s2_writedata>),                  //                                   .writedata
		.parameter_tx_ram_s2_byteenable                 (<connected-to-parameter_tx_ram_s2_byteenable>),                 //                                   .byteenable
		.parameterlengthpage_export                     (<connected-to-parameterlengthpage_export>),                     //                parameterlengthpage.export
		.parameterlengthpage_s1_address                 (<connected-to-parameterlengthpage_s1_address>),                 //             parameterlengthpage_s1.address
		.parameterlengthpage_s1_write_n                 (<connected-to-parameterlengthpage_s1_write_n>),                 //                                   .write_n
		.parameterlengthpage_s1_writedata               (<connected-to-parameterlengthpage_s1_writedata>),               //                                   .writedata
		.parameterlengthpage_s1_chipselect              (<connected-to-parameterlengthpage_s1_chipselect>),              //                                   .chipselect
		.parameterlengthpage_s1_readdata                (<connected-to-parameterlengthpage_s1_readdata>),                //                                   .readdata
		.pheriphal_clk_clk                              (<connected-to-pheriphal_clk_clk>),                              //                      pheriphal_clk.clk
		.pheriphal_reset_reset_n                        (<connected-to-pheriphal_reset_reset_n>),                        //                    pheriphal_reset.reset_n
		.cpu_clk_clk                                    (<connected-to-cpu_clk_clk>),                                    //                            cpu_clk.clk
		.cpu_reset_reset_n                              (<connected-to-cpu_reset_reset_n>),                              //                          cpu_reset.reset_n
		.parameter_gpio_external_in_port                (<connected-to-parameter_gpio_external_in_port>),                //            parameter_gpio_external.in_port
		.parameter_gpio_external_out_port               (<connected-to-parameter_gpio_external_out_port>),               //                                   .out_port
		.crc_init_bridge_avalon_slave_address           (<connected-to-crc_init_bridge_avalon_slave_address>),           //       crc_init_bridge_avalon_slave.address
		.crc_init_bridge_avalon_slave_byteenable        (<connected-to-crc_init_bridge_avalon_slave_byteenable>),        //                                   .byteenable
		.crc_init_bridge_avalon_slave_chipselect        (<connected-to-crc_init_bridge_avalon_slave_chipselect>),        //                                   .chipselect
		.crc_init_bridge_avalon_slave_read              (<connected-to-crc_init_bridge_avalon_slave_read>),              //                                   .read
		.crc_init_bridge_avalon_slave_write             (<connected-to-crc_init_bridge_avalon_slave_write>),             //                                   .write
		.crc_init_bridge_avalon_slave_writedata         (<connected-to-crc_init_bridge_avalon_slave_writedata>),         //                                   .writedata
		.crc_init_bridge_avalon_slave_readdata          (<connected-to-crc_init_bridge_avalon_slave_readdata>),          //                                   .readdata
		.crc_init_bridge_avalon_slave_waitrequest       (<connected-to-crc_init_bridge_avalon_slave_waitrequest>),       //                                   .waitrequest
		.crc_init_bridge_interrupt_irq                  (<connected-to-crc_init_bridge_interrupt_irq>),                  //          crc_init_bridge_interrupt.irq
		.crc_init_bridge_external_interface_acknowledge (<connected-to-crc_init_bridge_external_interface_acknowledge>), // crc_init_bridge_external_interface.acknowledge
		.crc_init_bridge_external_interface_irq         (<connected-to-crc_init_bridge_external_interface_irq>),         //                                   .irq
		.crc_init_bridge_external_interface_address     (<connected-to-crc_init_bridge_external_interface_address>),     //                                   .address
		.crc_init_bridge_external_interface_bus_enable  (<connected-to-crc_init_bridge_external_interface_bus_enable>),  //                                   .bus_enable
		.crc_init_bridge_external_interface_byte_enable (<connected-to-crc_init_bridge_external_interface_byte_enable>), //                                   .byte_enable
		.crc_init_bridge_external_interface_rw          (<connected-to-crc_init_bridge_external_interface_rw>),          //                                   .rw
		.crc_init_bridge_external_interface_write_data  (<connected-to-crc_init_bridge_external_interface_write_data>),  //                                   .write_data
		.crc_init_bridge_external_interface_read_data   (<connected-to-crc_init_bridge_external_interface_read_data>)    //                                   .read_data
	);

