	PatternGeneratorSYS u0 (
		.pd_clk_clk                (<connected-to-pd_clk_clk>),                //          pd_clk.clk
		.pd_debugram_s2_address    (<connected-to-pd_debugram_s2_address>),    //  pd_debugram_s2.address
		.pd_debugram_s2_chipselect (<connected-to-pd_debugram_s2_chipselect>), //                .chipselect
		.pd_debugram_s2_clken      (<connected-to-pd_debugram_s2_clken>),      //                .clken
		.pd_debugram_s2_write      (<connected-to-pd_debugram_s2_write>),      //                .write
		.pd_debugram_s2_readdata   (<connected-to-pd_debugram_s2_readdata>),   //                .readdata
		.pd_debugram_s2_writedata  (<connected-to-pd_debugram_s2_writedata>),  //                .writedata
		.pd_debugram_s2_byteenable (<connected-to-pd_debugram_s2_byteenable>), //                .byteenable
		.pd_fifo_out_readdata      (<connected-to-pd_fifo_out_readdata>),      //     pd_fifo_out.readdata
		.pd_fifo_out_read          (<connected-to-pd_fifo_out_read>),          //                .read
		.pd_fifo_out_waitrequest   (<connected-to-pd_fifo_out_waitrequest>),   //                .waitrequest
		.pd_fifo_out_csr_address   (<connected-to-pd_fifo_out_csr_address>),   // pd_fifo_out_csr.address
		.pd_fifo_out_csr_read      (<connected-to-pd_fifo_out_csr_read>),      //                .read
		.pd_fifo_out_csr_writedata (<connected-to-pd_fifo_out_csr_writedata>), //                .writedata
		.pd_fifo_out_csr_write     (<connected-to-pd_fifo_out_csr_write>),     //                .write
		.pd_fifo_out_csr_readdata  (<connected-to-pd_fifo_out_csr_readdata>),  //                .readdata
		.pd_gpio_in_port           (<connected-to-pd_gpio_in_port>),           //         pd_gpio.in_port
		.pd_gpio_out_port          (<connected-to-pd_gpio_out_port>),          //                .out_port
		.pd_reset_reset_n          (<connected-to-pd_reset_reset_n>),          //        pd_reset.reset_n
		.pheriphal_clk_clk         (<connected-to-pheriphal_clk_clk>),         //   pheriphal_clk.clk
		.pheriphal_reset_reset_n   (<connected-to-pheriphal_reset_reset_n>),   // pheriphal_reset.reset_n
		.reset_out_export          (<connected-to-reset_out_export>),          //       reset_out.export
		.pd_gpio_s1_address        (<connected-to-pd_gpio_s1_address>),        //      pd_gpio_s1.address
		.pd_gpio_s1_write_n        (<connected-to-pd_gpio_s1_write_n>),        //                .write_n
		.pd_gpio_s1_writedata      (<connected-to-pd_gpio_s1_writedata>),      //                .writedata
		.pd_gpio_s1_chipselect     (<connected-to-pd_gpio_s1_chipselect>),     //                .chipselect
		.pd_gpio_s1_readdata       (<connected-to-pd_gpio_s1_readdata>),       //                .readdata
		.pd_fifo_in_writedata      (<connected-to-pd_fifo_in_writedata>),      //      pd_fifo_in.writedata
		.pd_fifo_in_write          (<connected-to-pd_fifo_in_write>),          //                .write
		.pd_fifo_in_waitrequest    (<connected-to-pd_fifo_in_waitrequest>),    //                .waitrequest
		.pd_fifo_in_csr_address    (<connected-to-pd_fifo_in_csr_address>),    //  pd_fifo_in_csr.address
		.pd_fifo_in_csr_read       (<connected-to-pd_fifo_in_csr_read>),       //                .read
		.pd_fifo_in_csr_writedata  (<connected-to-pd_fifo_in_csr_writedata>),  //                .writedata
		.pd_fifo_in_csr_write      (<connected-to-pd_fifo_in_csr_write>),      //                .write
		.pd_fifo_in_csr_readdata   (<connected-to-pd_fifo_in_csr_readdata>),   //                .readdata
		.pd_debugram_s1_address    (<connected-to-pd_debugram_s1_address>),    //  pd_debugram_s1.address
		.pd_debugram_s1_clken      (<connected-to-pd_debugram_s1_clken>),      //                .clken
		.pd_debugram_s1_chipselect (<connected-to-pd_debugram_s1_chipselect>), //                .chipselect
		.pd_debugram_s1_write      (<connected-to-pd_debugram_s1_write>),      //                .write
		.pd_debugram_s1_readdata   (<connected-to-pd_debugram_s1_readdata>),   //                .readdata
		.pd_debugram_s1_writedata  (<connected-to-pd_debugram_s1_writedata>),  //                .writedata
		.pd_debugram_s1_byteenable (<connected-to-pd_debugram_s1_byteenable>), //                .byteenable
		.reset_pd_s1_address       (<connected-to-reset_pd_s1_address>),       //     reset_pd_s1.address
		.reset_pd_s1_write_n       (<connected-to-reset_pd_s1_write_n>),       //                .write_n
		.reset_pd_s1_writedata     (<connected-to-reset_pd_s1_writedata>),     //                .writedata
		.reset_pd_s1_chipselect    (<connected-to-reset_pd_s1_chipselect>),    //                .chipselect
		.reset_pd_s1_readdata      (<connected-to-reset_pd_s1_readdata>)       //                .readdata
	);

